let body = document.getElementById("myBody")
let nameToAdd = document.createElement("p")
let name = document.createTextNode("My name is Daniel.")
let heightToAdd = document.createElement("p")
let height = document.createTextNode("I am 6ft 5inches in height")
let countryToAdd = document.createElement("p")
let country = document.createTextNode("I am from Nigeria.")
nameToAdd.appendChild(name)
heightToAdd.appendChild(height)
countryToAdd.appendChild(country)
body.appendChild(nameToAdd)
body.appendChild(heightToAdd)
body.appendChild(countryToAdd)